"use client";

import { FormEvent, useEffect, useState } from "react";
import { Button, Input, Select, TextArea } from "@/components/ui/form";
import { GRADES } from "@/lib/utils";

export type ManageableUser = {
  id?: string;
  fullName: string;
  phone: string;
  username?: string | null;
  initialPassword?: string | null;
  secondaryPhone?: string | null;
  address?: string | null;
  grade?: string | null;
  phaseId?: string | null;
  classId?: string | null;
  birthDate?: string | Date | null;
  confessionFather?: string | null;
  fatherJob?: string | null;
  motherJob?: string | null;
  isMotherWorking?: boolean;
  totalPoints?: number;
};

export type PhaseChoice = { id: string; name: string; abbreviation: string };
export type ClassChoice = { id: string; name: string; phaseId: string };

function toDateInput(value?: string | Date | null) {
  if (!value) return "";
  const d = typeof value === "string" ? new Date(value) : value;
  if (Number.isNaN(d.getTime())) return "";
  return d.toISOString().slice(0, 10);
}

/**
 * Student (المخدوم) form — stage and class assignment plus full personal data.
 * Usernames and initial passwords are always generated by the server.
 */
export function UserForm({
  initial,
  mode,
  submitting,
  phases,
  classes,
  onSubmit,
}: {
  initial?: ManageableUser | null;
  mode: "create" | "edit";
  submitting?: boolean;
  phases: PhaseChoice[];
  classes: ClassChoice[];
  onSubmit: (payload: Record<string, unknown>) => Promise<void>;
}) {
  const [isMotherWorking, setIsMotherWorking] = useState(!!initial?.isMotherWorking);
  const [phaseId, setPhaseId] = useState<string>(initial?.phaseId ?? phases[0]?.id ?? "");

  useEffect(() => {
    setIsMotherWorking(!!initial?.isMotherWorking);
    setPhaseId(initial?.phaseId ?? phases[0]?.id ?? "");
  }, [initial, phases]);

  const phaseClasses = classes.filter((item) => item.phaseId === phaseId);

  async function handleSubmit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault();
    const fd = new FormData(e.currentTarget);
    await onSubmit({
      ...(initial?.id ? { id: initial.id } : {}),
      fullName: String(fd.get("fullName") || ""),
      phone: String(fd.get("phone") || ""),
      secondaryPhone: String(fd.get("secondaryPhone") || "") || null,
      address: String(fd.get("address") || "") || null,
      grade: String(fd.get("grade") || "") || null,
      phaseId: phaseId || null,
      classId: String(fd.get("classId") || "") || null,
      birthDate: String(fd.get("birthDate") || "") || null,
      confessionFather: String(fd.get("confessionFather") || "") || null,
      fatherJob: String(fd.get("fatherJob") || "") || null,
      isMotherWorking,
      motherJob: isMotherWorking ? String(fd.get("motherJob") || "") || null : null,
      pin: String(fd.get("pin") || "") || null,
      regenerateCredentials: fd.get("regenerateCredentials") === "on",
    });
  }

  return (
    <form onSubmit={handleSubmit} className="space-y-3">
      <Input name="fullName" label="الاسم الرباعي" required defaultValue={initial?.fullName || ""} />
      <Input name="phone" label="رقم التليفون" required inputMode="tel" defaultValue={initial?.phone || ""} />
      <Input
        name="secondaryPhone"
        label="رقم تليفون إضافي / ولي الأمر"
        inputMode="tel"
        defaultValue={initial?.secondaryPhone || ""}
      />
      <TextArea name="address" label="العنوان" defaultValue={initial?.address || ""} />

      <Select label="المرحلة" value={phaseId} onChange={(e) => setPhaseId(e.target.value)} required>
        <option value="" disabled>
          اختر المرحلة
        </option>
        {phases.map((phase) => (
          <option key={phase.id} value={phase.id}>
            {phase.name} ({phase.abbreviation})
          </option>
        ))}
      </Select>

      <Select name="classId" label="الفصل (اختياري)" defaultValue={initial?.classId ?? ""}>
        <option value="">بدون فصل</option>
        {phaseClasses.map((item) => (
          <option key={item.id} value={item.id}>
            {item.name}
          </option>
        ))}
      </Select>

      <Select name="grade" label="المرحلة الدراسية" defaultValue={initial?.grade || phases[0]?.name || ""}>
        {GRADES.map((g) => (
          <option key={g} value={g}>
            {g}
          </option>
        ))}
      </Select>

      <Input name="birthDate" label="تاريخ الميلاد" type="date" defaultValue={toDateInput(initial?.birthDate)} />
      <Input name="confessionFather" label="أب الاعتراف" defaultValue={initial?.confessionFather || ""} />
      <Input name="fatherJob" label="وظيفة الأب" defaultValue={initial?.fatherJob || ""} />
      <label className="flex items-center gap-3 rounded-2xl border border-slate-200 bg-white px-4 py-3">
        <input
          type="checkbox"
          checked={isMotherWorking}
          onChange={(e) => setIsMotherWorking(e.target.checked)}
          className="h-4 w-4 accent-[var(--color-emerald)]"
        />
        <span className="text-sm font-semibold">هل الأم تعمل؟</span>
      </label>
      {isMotherWorking && <Input name="motherJob" label="وظيفة الأم" defaultValue={initial?.motherJob || ""} />}

      <Input
        name="pin"
        label={mode === "create" ? "الرقم السري PIN (اختياري للدخول بالـ PIN)" : "تغيير PIN (اختياري)"}
        type="password"
        minLength={4}
        maxLength={8}
      />

      {mode === "edit" && (
        <label className="flex items-center gap-3 rounded-2xl border border-slate-200 bg-white px-4 py-3">
          <input type="checkbox" name="regenerateCredentials" className="h-4 w-4 accent-[var(--color-emerald)]" />
          <span className="text-sm font-semibold">توليد كلمة مرور أولية جديدة</span>
        </label>
      )}

      <p className="rounded-2xl bg-slate-50 p-3 text-xs leading-relaxed text-slate-600">
        يتم توليد اسم المستخدم وكلمة المرور تلقائياً بصيغة{" "}
        <span className="font-mono">{"{church}_user_{5}"}</span> ويُعرضان بعد الحفظ.
      </p>

      <Button type="submit" className="w-full" disabled={submitting}>
        {submitting ? "جارٍ الحفظ..." : mode === "create" ? "إضافة المخدوم" : "حفظ التعديلات"}
      </Button>
    </form>
  );
}

